// 리스트 생성 관련
export const imgData = [
  {
    src: "img/2020/CAFE_NURI/nuri10.jpg",
    text: "광주 광산구",
    info: "CAFE NURI",
    description: "Portfolio",
    link: "detailPage/cafeNuri.html",
    customClass: "cafe",
  },
  {
    src: "img/2020/MYNEE_NAIL/IMG_6540.JPG",
    text: "광주 북구",
    info: "MYNEE NAIL",
    link: "detailPage/myneeNail.html",
    customClass: "nailShop",
  },
  {
    src: "img/2020/USEFUL/useful4.JPG",
    text: "광주 동구",
    info: "USEFUL",
    link: "detailPage/useful.html",
    customClass: "store",
  },
  {
    src: "img/2021/molito/molito_main.jpg",
    text: "광주 서구",
    info: "Molito",
    link: "detailPage/molito.html",
    customClass: "studio",
  },
  {
    src: "img/2021/Aube/SZ_02864.jpg",
    text: "광주 남구",
    info: "Aubu",
    link: "detailPage/aube.html",
    customClass: "hairShop",
  },
  {
    src: "img/2022/monello/19.jpg",
    text: "광주 중구",
    info: "MONELLO",
    link: "detailPage/monello.html",
    customClass: "store",
  },
  {
    src: "img/2022/bagel_bazel/bagel_main.jpg",
    text: "광주 광산구",
    info: "bagel bazel",
    link: "detailPage/bagelBazel.html",
    customClass: "cafe",
  },
  {
    src: "img/2022/yookjihyang/yook_main.jpg",
    text: "광주 남구",
    info: "육지향",
    link: "detailPage/yugjihyang.html",
    customClass: "restaurant",
  },
  {
    src: "img/2022/theessentialhouse/theessentialhouse1.jpg",
    text: "광주 동구",
    info: "THE ESSENTIAL HOUSE",
    description: "",
    link: "detailPage/theessentialhouse.html",
    customClass: "wineShop",
  },
  {
    src: "img/2020/LE_CAFE_SEASON/lecafeseason4.JPG",
    text: "광주 서구",
    info: "LE CAFE SEASON",
    link: "detailPage/leCafeSeason.html",
    customClass: "cafe",
  },
  {
    src: "img/2020/TOV_COFFEE/tov13.JPG",
    text: "광주 광산구",
    info: "TOV COFFEE",
    description: "",
    link: "detailPage/tovcoffee.html",
    customClass: "cafe",
  },
  {
    src: "img/2022/teresa/teresa.JPG",
    text: "광주 동구",
    info: "TERESA",
    link: "detailPage/teresa.html",
    customClass: "store",
  },
  {
    src: "img/2022/hotel_core_kidsPoolVilla/A058.jpg",
    text: "나주 빛가람동",
    info: "HOTEL CORE KP Villa",
    link: "detailPage/hotelCoreKidsPoolVilla.html",
    customClass: "hotel",
  },
  {
    src: "img/2022/EARLY_DAWN/004.jpg",
    text: "광주 광산구",
    info: "EARLY DAWN",
    link: "detailPage/earlyDawn.html",
    customClass: "store",
  },
  {
    src: "img/2022/dear_hair_salon/dear013.jpg",
    text: "광주 남구",
    info: "DEAR HAIR SALON",
    link: "detailPage/dearHairSalon.html",
    customClass: "beautyShop",
  },
  {
    src: "img/2024/sodam_maru/003.jpeg",
    text: "광주",
    info: "소담마루",
    link: "detailPage/sodamMaru.html",
    customClass: "store",
  },
];
